### PR TITLE
Add flow

### PR DESCRIPTION
**Pull request by yavorsky**
Also replaced uglify with useSyntax like in https://github.com/babel/babel-preset-env/pull/264 and will pull changes after `use-syntax-option` into `2.0` merge.

### CODE REVIEW

**Comment by existentialism** [comment]
@yavorsky mind rebasing?

**Comment by yavorsky** [comment]
@existentialism yeah, on it

**Comment by existentialism** [comment]
@yavorsky hope you don't mind, wanted to get this landed so I resolved the conflicts.

Small tweaks:

- Bumped flow to 0.45
- Reverted renaming `modules` to `moduleType` (we can do that separately, as we may want to discuss whether or not we want that breaking change, whether to preserve backwards compatibility, and consistency with other presets, etc)

Otherwise, your changes look awesome, mind giving this a review?

**Comment by yavorsky** [comment]
@existentialism Oh, thanks!
Yeah. I think it's ready to be merged. 🕺

**Pull request merged**
