### PR TITLE
Add OS X builds to Travis

### PR DESCRIPTION
**Pull request by hawkrives**
This first attempt might fail, but I've gotten it working before.

(For #39)

### CODE REVIEW

**Comment by hawkrives** [comment]
The downside to testing on OS X is that Travis's OS X build queue is usually full:

screen shot 2016-11-08 at 11 33 58 am

(It usually fills right back up at around 7am. Today seems to be slow.)

**Comment by danez** [comment]
Maybe we could only run latest node on mac os?

**Comment by hawkrives** [comment]
I thought about that, but #39 mentioned a bug with node@4 on OS X so…

**Comment by hzoo** [comment]
can do allow_failures toohttps://github.com/sheerun/modern-node/blob/master/.travis.yml#L18-L19 cc @sheerun

**Comment by hawkrives** [comment]
If we do `allow_failures`, will the build status here note that? Will anyone ever see when the OS X build fails?

**Comment by sheerun** [comment]
I think you shound't ignore failed osx builds

**Comment by hzoo** [comment]
Although babel-preset-env's own tests are regarding manipulating the plugins and don't actually run anything. We don't have any integration type tests

**Comment by sheerun** [comment]
Well, you could have :)

**Comment by hzoo** [comment]
Most babel tests themselves don't actual do an exec test - mostly a string check that `transform(actual) === expected`

**Comment by sheerun** [comment]
Ideally there would be an example app that uses all of es6 features, you compile it for different environments, and run it there. Maybe @browserstack or @saucelabs could sponsor

**Comment by hzoo** [comment]
Were using the data from compat-table so we trust that it is correct on there but yeah would be nice!

**Comment by hzoo** [comment]
Let's come back to this when we setup exec tests if we need to

**Pull request closed without merging**
