### PR TITLE
Enable code coverage

### PR DESCRIPTION
**Pull request by alxpy**
I propose to add code coverage to this repo.
Can someone from members enable integration with `codecov.io`?

### CODE REVIEW

**Comment by alxpy** [comment]
> codecov/project — No report found to compare against

I think it's OK for the first PR with `codecov`

**Comment by existentialism** [comment]
Couple things:

- Probably want to _only_ include `src`, no sense in doing coverage on the data files, etc.

- Should set `all: true` to include any files that don't have any tests

- To get better coverage results, let's instrument the code via `babel-plugin-instanbul` (via BABEL_ENV/NODE_ENV).

**Comment by alxpy** [comment]
@existentialism done.
But it looks like `babel-plugin-instanbul` does not work with `Node.js 0.10/0.12`. Should we support the `Node.js 0.10/0.12`?

**Comment by existentialism** [comment]
@alxpy for master we should use 3.1.2, and can bump to 4.0 on `2.0`, if you don't mind making that change, I'll follow it up with some tweaks for CI/documentation.

**Comment by existentialism** [comment]
@alxpy made a few tweaks, please review!

**Comment by alxpy** [comment]
@existentialism LGTM!

**Comment by existentialism** [comment]
@alxpy thanks again!

**Pull request merged**
