### PR TITLE
Add target presets option

### PR DESCRIPTION
**Pull request by rtsao**
Fixes https://github.com/babel/babel-preset-env/issues/91

### CODE REVIEW

**Comment by rtsao** [comment]
Travis tests are passing on Node versions `4` and `7` but failing on `0.10`, `0.12`, and `6`, which I find puzzling. Locally, tests are passing on Node 6 for me.

It seems the the failing cases are caused by inconsistency of `"use strict"` being inserted. For example:

```diff
+'use strict';
+
const a = Math.pow(1, 2);
 
const b = () => 'foo';
```

**Comment by hzoo** [comment]
Yeah this works but I think we can just simply add the stage-3 plugins manually as deps rather than use the preset itself - there were also thoughts of removing presets or renaming since it changed so much so not sure.

**Comment by rtsao** [comment]
Makes sense to me.

I had the idea of allowing this work with arbitrary presets and prevent this package from needing to care about which plugins belong to which preset. However, this is probably more complex than it's worth.

**Comment by hzoo** [comment]
@rtsao I think we can totally do this just adding the plugins individually if you still want to do it

**Pull request closed without merging**
