### PR TITLE
Remove unnecessary extension

### PR DESCRIPTION
**Pull request by roman-yakobnyuk**
Removed unnecessary `.js` extension and fixed tests.

### CODE REVIEW

**Comment by hzoo** [comment]
Ok this looks great!

I just realized I gave the wrong instructions though so we need to change https://github.com/babel/babel-preset-env/blob/master/data/built-in-features.js#L123 too

```js
const es2016 = {
  "es7.array.includes.js": "Array.prototype.includes",
};
```

**Comment by roman-yakobnyuk** [comment]
Updated the branch to include this change too, all tests seem fine too.

**Comment by existentialism** [comment]
Nice work @roman-yakobnyuk!

**Comment by hzoo** [comment]
yeah `data/built-in-features.js` is the data and the other file is generated but didn't want to make it too complicated - will merge once CI passes.

**Comment by hzoo** [comment]
Oh yeah a tip: you can put `Fixes #issue-number-here` in the description/commit message and it will automatically close the corresponding issue.

**Comment by roman-yakobnyuk** [comment]
Will keep that in mind for future, thanks!

**Comment by skattyadz** [comment]
Just so you're aware, this PR caused our config to break. It's easy to fix but I wonder if this could have been a minor server bump

**Comment by hzoo** [comment]
I had no idea @skattyadz, I'm not sure why I had it originally and so I figured it was unnecessary (thus no reason for just a patch bump). 

Can you explain the error and all that?

**Pull request merged**
