### PR TITLE
Add transform-duplicate-keys mapping

### PR DESCRIPTION
**Pull request by existentialism**
Thanks to @Timer, it looks like we missed mapping this transform causing output to be different than `preset-latest`.

I double checked that the rest of the plugins are mapped.

Ref: https://github.com/facebookincubator/create-react-app/pull/1742

### CODE REVIEW

**Comment by Timer** [comment]
You're a saint. Thanks!

**Comment by yavorsky** [comment]
@hzoo We are not testing all plugins (just opts for `regenerator` and `transform-polyfill-require-plugin`), so I think it's not necessarily. Updating `stdout.txt` should be ok. Or we could add tests to cover all or most of plugins.
Mabye let's test matching latest without targets?

**Comment by Timer** [comment]
Anything I can do to help?

**Comment by existentialism** [comment]
Added a quick and dirty sanity check test, it doesn't hurt to have these until we move to more comprehensive tests on Browserstack or some other means.

**Pull request merged**
