### PR TITLE
Fix transform-polyfill-require transformed paths

### PR DESCRIPTION
**Pull request by romulof**
It was importing stuff from outside `library` folder.

### CODE REVIEW

**Comment by yavorsky** [comment]
Hi, @romulof, thanks for the PR!

Trying to understand why it's better to use 'library/modules' location. Did you have some troubles with imports?

If yes, we must fix all the tests which requires 'core-js/modules/[feature]' imports.

**Comment by romulof** [comment]
All other libraries and dependencies import from `core-js/library/...`, so when preset-env imports from `core-js/modules` some modules get duplicated.

The original core-js documentation states to import from `library` dir.

This simple fix has shrunk my bundle ~10kB.

**Comment by hzoo** [comment]
cc @zloirock so we should be using /library? I didn't know

**Comment by zloirock** [comment]
Nope, here should be `core-js/modules`, not `core-js/library/modules`. `library` is a version without global namespace pollution, but it's a regular polyfill.

**Comment by romulof** [comment]
@zloirock, thanks for the explanation. I'll see which libraries are using the "wrong" version.

**Pull request closed without merging**
