### PR TITLE
add maintained node target Fixes #341

### LINKED ISSUE #341: option for node: 'maintained' that enables rules for the oldest maintained node version.
See this chart for maintenance cycle: https://github.com/nodejs/LTS

### PR DESCRIPTION
**Pull request by graingert**
these flags suggest that users with babel-register should use 'current' and `babel src dist` should use 'maintained'

### CODE REVIEW

**Comment by hzoo** [comment]
cc @mylesborins on thoughts on this option in general (and I guess hardcoding is ok?).

Not sure about this option because at some point (the day of the switch), it will just target the next version even if you yourself haven't updated? Unless we should assume that if you pick this option it means that you intend to upgrade beforehand?

**Comment by graingert** [comment]
@hzoo the same problems exist with browser version ranges

**Comment by graingert** [comment]
If we're going to go with hard-coding I'll make a build script that runs pulls the data out of https://github.com/nodejs/LTS/blob/master/schedule.json

**Comment by niieani** [comment]
I think it would be better to call this option "lts" instead of "maintained". after all non-LTS are also _maintained_, just not _supported_. Another option would be that very word: "supported".

**Comment by graingert** [comment]
@niieani I don't mind about the word

**Comment by existentialism** [comment]
Let's go with `lts`.

> If we're going to go with hard-coding I'll make a build script that pulls the data out of https://github.com/nodejs/LTS/blob/master/schedule.json

👍

**Comment by hzoo** [comment]
Thanks for the PR! 

> Now that babel-preset-env has stabilized, it has been moved into the main Babel mono-repo.
> The move makes it much easier to release and develop in sync with the rest of Babel!

This repo will be made read-only, as all of the issues/labels have been moved over as well. Please report any bugs and open pull requests over on the main mono-repo (against master which is v7)

**Pull request closed without merging**
