### PR TITLE
Fixes #143. Log correct targets.

### LINKED ISSUE #143: [bug]? still use plugin < target version
`babel-preset-env: `DEBUG` option`

```
Using targets:
{
  "firefox": 52,
  "node": 7.4 
}

Modules transform: commonjs

Using plugins:
  transform-es2015-destructuring {"node":6.5} // node is 7.4 , but still use 6.5 plugin
  transform-es2015-for-of {"node":6.5}
  transform-es2015-function-name {"node":6.5}
  transform-es2015-literals {"node":4}
  transform-exponentiation-operator {"firefox":52}
  syntax-trailing-function-commas {"firefox":52}
```

```
{
  "presets": [
    [
      "env",
      {
        "debug": true,
        "exclude": [
          "transform-async-to-generator",
          "transform-regenerator", "transform-es2015-parameters"
        ],
        "targets": {
          "firefox": 52,
          "node": 7.4
        }
      }
    ]
  ]
}
```

### PR DESCRIPTION
**Pull request by yavorsky**
Fixes https://github.com/babel/babel-preset-env/issues/143

### CODE REVIEW

**Comment by hzoo** [comment]
Did we already make an issue for debug tests?

**Comment by yavorsky** [comment]
@hzoo No, just your comment in the [closed PR](https://github.com/babel/babel-preset-env/pull/128#issuecomment-271634627).

**Comment by hzoo** [comment]
That linked to https://github.com/babel/babel-preset-env/issues/133 so yes?

**Comment by yavorsky** [comment]
@hzoo Oh, really, sorry

**Comment by yavorsky** [comment]
If no one take it, I could after [decorators issue](https://github.com/babel/babel/issues/5220).

**Comment by existentialism** [comment]
@yavorsky I have a crude version for running the debug tests (I tested it on this fix), will push soon!

**Comment by yavorsky** [comment]
@existentialism Cool!  🎉 👍

**Pull request merged**
